# MySQL \uC5F0\uACB0
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/quiz

# \uD658\uACBD\uC124\uC815 \uD30C\uC77C\uC5D0\uC11C \uD658\uACBD\uBCC0\uC218\uB97C \uB9CC\uB4DC\uB294 \uBC95
spring.datasource.username=${DB_USER:root}
spring.datasource.password=${DB_PW:1111}

# Hibernate SQL \uB85C\uADF8
spring.jpa.properties.hibernate.show_sql=true
spring.jpa.properties.hibernate.format_sql=true

# \uD14C\uC774\uBE14 \uC790\uB3D9 \uC0DD\uC131 \uC804\uB7B5
# \uC644\uC804 \uAC1C\uBC1C \uCD08\uAE30 : Create
# \uAC1C\uBC1C \uCD08\uAE30 / \uC911\uAE30 : Update
# validate : DB \uC548\uC815\uD654
# none : \uBC30\uD3EC
spring.jpa.hibernate.ddl-auto= update

# SQL \uBC14\uC778\uB529 \uD30C\uB77C\uBBF8\uD130 \uB85C\uADF8
logging.level.org.hibernate.type.descriptor.sql=trace

# MySQL \uBC29\uC5B8 \uC124\uC815
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect